### ISSUE TITLE
MkDocs output

### ISSUE THREAD

**Issue by gillchristian** [gillchristian/docs-ts-extra#6]
- [ ] Generate config file
- [ ] Update markdown files template to MkDocs format
- [ ] Introduce config to output different _templates_

**Comment by gillchristian** [comment]
```yml
site_name: projects/cw-cli
theme:
  name: material
  palette:
    scheme: default
    primary: white
  features:
    - navigation.tabs
nav:
  - Overview: index.md
  - Modules:
    - config.ts: modules/config.ts.md
    - markdown.ts: modules/markdown.ts.md
```

Check extensions and plugins

```yml
markdown_extensions: # https://python-markdown.github.io/extensions/
  - admonition
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - footnotes
  - markdown_checklist.extension
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
plugins:
    - search
    - monorepo
```
